language: cpp
matrix:
  include:
    - os: osx
      osx_image: xxcode9.1
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - sdl2_ttf
    - os: linux
      dist: xenial
      compiler: clang
      addons:
        apt:
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
    - os: windows
      before_install:
        - wget https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip -O extern/SDL2.zip
        - cd extern
        - unzip SDL2.zip
        - ls

install:
  - JOBS=2
  - BUILD_TYPE=Release
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build .
