language: cpp
matrix:
  include:
    - os: osx
      osx_image: xxcode9.1
    - os: linux
      dist: trusty
    - os: windows

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
  homebrew:
    packages:
      - sdl2
      - sdl2_image
      - sdl2_ttf

install:
  - JOBS=2
  - BUILD_TYPE=Release
  - cmake --version

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build . -- -j${JOBS}
